web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: library/mysql:5.6.22
  volumes:
        - ./docker/mariadb:/etc/mysql/conf.d
        - ./docker/mariadb/data:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
        MYSQL_ROOT_PASSWORD: 38difj3jD19dkDIEFKINE93
        MYSQL_USER: railsapi
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: railsapi

