# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efeab51335f61cf2c197dbee682427d43921228b322437f6203803aa2495049490e74f43e016d23ebfb3d3a9297436cd32d1ca647332a7571f0969f8d1cef39a

test:
  secret_key_base: 3a8d9bf2d71c4e9351b6036bace9b157f2862f57a2f59fc4f57c1c0629375d1db973b8691bb6c23812dc622fe1680a0a32f00b3fea6040729b6b37cb71c9ebaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
